<h1>Danayal Khan 
b00069350</h1>

<h3>Lab 4 - Deep Learning and Neural Networks</h3>

In [1]:
import numpy as np

In [2]:
# Exercise: 1 Lab 4

def relu(X):
   return np.maximum(0,X)

def loss(x,y):
    return abs(x-y)

# using arbirary weights
w1 = np.array([0.9])
w2 = np.array([0.9])

print("w1 = \n", w1,"\n\n w2 = \n", w2)


def forward(a0, weight1, weight2):
    z1 = np.dot(a0, weight1)
    a1 = relu(z1)
    z2 = np.dot(a1, weight2)
    a2 = relu(z2)
    print ("\na0 = ", a0, "\n\nz1 = ", z1, "\n\na1 = " ,a1, "\n\nz2 = " , z2 , "\n\na2 = " , a2)

    #return loss(a2[0][0],y)

a0 = np.array([2])

forward(a0,w1, w2)




w1 = 
 [0.9] 

 w2 = 
 [0.9]

a0 =  [2] 

z1 =  1.8 

a1 =  1.8 

z2 =  [1.62] 

a2 =  [1.62]


In [3]:
#Exercise: 2 Lab 4


def relu(X):
   return np.maximum(0,X)

def loss(x,y):
    return abs(x-y)

# using arbirary weights
#subtracting by -0.5 to get negative values as well. np.random.random() by default returns values between 0 and 1

w1 = 5 * ( np.random.random((1,3)) -0.5 ) 
w2 = 5 * ( np.random.random((3,1)) -0.5 ) 


print("w1 = \n", w1,"\n\n w2 = \n", w2)




def forward(a0, weight1, weight2):
    z1 = np.dot(a0, weight1)
    a1 = relu(z1)
    z2 = np.dot(a1, weight2)
    a2 = relu(z2)

    
    print ("\na0 = ", a0, "\n\nz1 = ", z1, "\n\na1 = " ,a1, "\n\nz2 = " , z2 , "\n\na2 = " , a2)


a0 = np.array([2])

forward(a0,w1, w2)







w1 = 
 [[-1.66603665  2.43597174  2.20646597]] 

 w2 = 
 [[0.07772933]
 [2.14712963]
 [1.42983296]]

a0 =  [2] 

z1 =  [-3.33207329  4.87194347  4.41293194] 

a1 =  [0.         4.87194347 4.41293194] 

z2 =  [16.77044972] 

a2 =  [16.77044972]


In [4]:
#Exercise: 3 Lab 4


def relu(X):
   return np.maximum(0,X)

def loss(x,y):
    return abs(x-y)

# using arbirary weights
#subtracting by -0.5 to get negative values as well. np.random.random() by default returns values between 0 and 1

w1 = 5 * ( np.random.random((4,2)) -0.5 ) 
w2 = 5 * ( np.random.random((2,3)) -0.5 ) 


print("w1 = \n", w1,"\n\n w2 = \n", w2)




def forward(a0, weight1, weight2):
    z1 = np.dot(a0, weight1)
    a1 = relu(z1)
    z2 = np.dot(a1, weight2)
    a2 = relu(z2)

    
    print ("\na0 = ", a0, "\n\nz1 = ", z1, "\n\na1 = " ,a1, "\n\nz2 = " , z2 , "\n\na2 = " , a2)


a0 = np.random.random(4)

forward(a0,w1, w2)







w1 = 
 [[-0.87005068 -1.58997409]
 [ 1.23292953  2.46232028]
 [ 1.74379668  0.57444651]
 [ 0.04148326  1.97511152]] 

 w2 = 
 [[ 0.14473889  0.16505019 -1.26457538]
 [ 0.01379651  1.09901151  1.77594831]]

a0 =  [0.81264657 0.30701806 0.98004804 0.72382271] 

z1 =  [1.41051895 1.45650554] 

a1 =  [1.41051895 1.45650554] 

z2 =  [0.22425164 1.83352278 0.80297102] 

a2 =  [0.22425164 1.83352278 0.80297102]
