In [3]:
# Please make sure all the libraries are installed

import sys
!{sys.executable} -m pip install numpy

import numpy as np

In [10]:
# Create a simple array 
a = np.array([[1,2,3,4], [5,6,7,8]])
a



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# Let us view different attributes of this array 

# Print out the dimension of the array -- This is a two dimensional array
print(a.ndim)

# Print out memory address (pointer) - some arbitrary pointer
print(a.data)

# Print out the shape (row, columns) - this has two rows and 4 columns
print(a.shape)

# Print out the data type (e.g., int64) - is integer 64
print(a.dtype)

# Print out the stride. 8 bytes to get to the next element because it is int64 (which is 8 bytes each)
# Since there are 4 elements in each row, need to skip 4x8 = 32 bytes to get to the next row. 
print(a.strides)


2
(2, 4)
int64
(32, 8)


In [15]:
#Exercise: Create a 1-D array and explain all it's attributes. 

# Create a simple array 
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [16]:
# Let us view different attributes of this array 

# Print out the dimension of the array -- This is a one dimensional array
print(b.ndim)

# Print out memory address (pointer) - some arbitrary pointer
print(b.data)

# Print out the shape (row, columns) - this is strange in that it has four rows and no columns.
print(b.shape)

# Print out the data type (e.g., int64) - is integer 64
print(b.dtype)

# Print out the stride. 8 bytes to get to the next element because it is int64 (which is 8 bytes each)
# No columns so no bytes to get to the next row. 
print(b.strides)

1
(4,)
int64
(8,)


In [17]:
#Exercise: Create a 2-D array with a single row and explain it's attributes

# Create a simple array. Compare this to the 1-D from before and see the difference. 
c = np.array([[1,2,3,4]])
c

array([[1, 2, 3, 4]])

In [18]:
# Let us view different attributes of this array 

# Print out the dimension of the array -- This is a 2 dimensional array
print(c.ndim)

# Print out memory address (pointer) - some arbitrary pointer
print(c.data)

# Print out the shape (row, columns) - It has 1 row and 4 columns
print(c.shape)

# Print out the data type (e.g., int64) - is integer 64
print(c.dtype)

# Print out the stride. 8 bytes to get to the next element because it is int64 (which is 8 bytes each)
# 32 bytes to go to the next row. 
print(c.strides)

2
(1, 4)
int64
(32, 8)


In [19]:
# Let us do a 3 dimensional array with all zero's inside. 

a = np.zeros((2, 3, 4))
a


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# Exercise: Can you explain what number corresponds to row, column and depth?

# 2 = depth
# 3 = rows
# 4 = columns


In [20]:
# Let us view different attributes of this array 

# Print out the dimension of the array -- This is a 2 dimensional array
print(a.ndim)

# Print out memory address (pointer) - some arbitrary pointer
print(a.data)

# Print out the shape (row, columns) - It has 3 rows, 4 columns and a depth of 2. 
print(a.shape)

# Print out the data type (e.g., int64) - is integer 64
print(a.dtype)

# Print out the stride. 8 to go to next element, 32 to go to next row, 96 to go to next depth. 
print(a.strides)

3
(2, 3, 4)
float64
(96, 32, 8)


In [21]:
# Let us do a 4 dimensional array with all zero's inside. 

a = np.zeros((2, 3, 4, 5))
a

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [ ]:
# Exercise: Can you explain what number corresponds to row, column, and depth0 and depth1?

# 2 = depth0
# 3 = depth1
# 4 = rows
# 5 = columns

In [23]:
# Create an array of ones
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# Create an array of zeros
b = np.zeros((2,3,4),dtype=np.int16)
b

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [25]:
# Create an array with random values
c = np.random.random((2,2))
c


array([[0.64942916, 0.54286891],
       [0.93040992, 0.80359044]])

In [26]:
# Create an empty array
d = np.empty((3,2))
d

array([[ 2.31584178e+077, -1.49457509e-154],
       [ 1.48219694e-323,  0.00000000e+000],
       [ 0.00000000e+000,  4.17201348e-309]])

In [27]:
# Create a full array
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [51]:
# Create an array of evenly-spaced values 10 to 25 by 5
f= np.arange(10,25,5)
f

array([10, 15, 20])

In [29]:
# Create an array of evenly-spaced values from 0 to 2 in nine increments
g = np.linspace(0,2,9)
g

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
# Create adentity matrix diagonal is all zeros
h= np.eye(10,10)
h

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
# We can change the type of an array using as_type
e = np.full((2,2),7,dtype=np.int16)
print(e)
e = e.astype('float64') 
print(e)

[[7 7]
 [7 7]]
[[7. 7.]
 [7. 7.]]


In [40]:
# Example 1 of reshape
x = np.array([[2,3,4], [5,6,7]])      
y = np.reshape(x, (3, 2))
print(y)


[[2 3]
 [4 5]
 [6 7]]


In [43]:
# Example 2 of reshape

x = np.array([[2,3,4], [5,6,7]]) 
y = np.reshape(x, (2, -1)) 

print(y)

[[2 3 4]
 [5 6 7]]


In [45]:
# Exercise -  create an array of a single column from x

z = np.reshape(x, (-1, 1)) 
print(z)

[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [46]:
# Example 3 of reshape

x = np.array([[2,3,4], [5,6,7]]) 
y = np.reshape(x, (3, -1))

print(y)

[[2 3]
 [4 5]
 [6 7]]


In [47]:
# Example 4 - going to 1-D

x = np.array([[2,3,4], [5,6,7]])
y = np.reshape(x, 6)

print(y)


[2 3 4 5 6 7]


In [55]:
# Exercise - Create 3 rows, 3 columns and depth = 2 array from x

x = np.arange(18)
x
y = np.reshape(x,(2,3,3))
y


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [57]:
# Exercise - Create a 1x2x3 array from x
x = np.array([[1,2],[3,4],[5,6]])
x
y = np.reshape(x,(1,2,3))
y

array([[[1, 2, 3],
        [4, 5, 6]]])

In [91]:
# We can resize an array with padding

A = np.array([[1,0,2,0],[0,3,0,4],[0,0,5,0],[6,0,0,7]])

B = np.resize(A,(5,5))

# Pads with zeroes
print(B)

[[1 0 2 0 0]
 [3 0 4 0 0]
 [5 0 6 0 0]
 [7 1 0 2 0]
 [0 3 0 4 0]]


In [93]:
# Can we resize with smaller size

A = np.array([[1,0,2,0],[0,3,0,4],[0,0,5,0],[6,0,0,7]])

B = np.resize(A,(3,3))

# Pads with zeroes
print(B)


[[1 0 2]
 [0 0 3]
 [0 4 0]]


In [94]:
# Flattening an array 

A = np.array([[1,0,2,0],[0,3,0,4],[0,0,5,0],[6,0,0,7]])
z = A.ravel()

print(z)


[1 0 2 0 0 3 0 4 0 0 5 0 6 0 0 7]


In [60]:
# Adding two arrays

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])

z = x+y
print(z)

[[ 8 10 12]
 [14 16 18]]


In [61]:
# Subtracting two arrays

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])

z = x-y
print(z)

[[-6 -6 -6]
 [-6 -6 -6]]


In [62]:
# Multiplying by a scalar

x = np.array([[1,2,3],[4,5,6]])
y = 0.5

z = x*y
print(z)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [69]:
# Array multipliction example

A = np.array([[1,2],[3,4]],dtype=np.float)
B = np.array([[5,6],[7,8]],dtype=np.float)

print(A)
print(B)


C = A*B

print(C)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 5. 12.]
 [21. 32.]]


In [71]:
# Matrix multipliction example

A = np.array([[1,2],[3,4]],dtype=np.float)
B = np.array([[5,6],[7,8]],dtype=np.float)

print(A)
print(B)


C = np.dot(A,B)

print(C)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[19. 22.]
 [43. 50.]]


In [82]:
# Transposing an array as a matrix

a = np.array([[3,-4],[2,0],[-1,6],[5,1]])
print(a)
b = a.T
print(b)

[[ 3 -4]
 [ 2  0]
 [-1  6]
 [ 5  1]]
[[ 3  2 -1  5]
 [-4  0  6  1]]


In [85]:
# Multiplying a matrix with a vector using arrays

A = np.array([[1,0,2,0],[0,3,0,4],[0,0,5,0],[6,0,0,7]])
x = np.array([2,5,1,8])

B = np.dot(A,x)

print(B)

[ 4 47  5 68]


In [89]:
# Multiplying a matrix with a vector using arrays and transposing

A = np.array([[1,0,2,0],[0,3,0,4],[0,0,5,0],[6,0,0,7]])
x = np.array([[2,5,1,8]])

# transpose x so it can be multiplied
x = x.T

# multiply
B = np.dot(A,x)

# reshape B into a 1-D vector
B = B.reshape(4)
print(B)

[ 4 47  5 68]


In [79]:
# Doing logical operators with arrays 

a = np.array([[1,2],[3,4]])
b = np.eye(2,2)

c = np.logical_and(a,b)
print(c)

# convert back to int
d = c.astype('int16')
print(d)

[[ True False]
 [False  True]]
[[1 0]
 [0 1]]


In [80]:
# Comparing two arrays

a = np.array([[1,2],[3,4]])
b = np.eye(2,2)

c = np.dot(a,b)

print(np.array_equal(a,c))


True


In [103]:
# Taking the max of the array
A = np.array([[1,0,2,0],[0,3,0,4],[0,0,5,0],[6,0,0,7]])

print(A)

print(A.max())
print(A.max(0))
print(A.max(1))

[[1 0 2 0]
 [0 3 0 4]
 [0 0 5 0]
 [6 0 0 7]]
7
[6 3 5 7]
[2 4 5 7]


In [118]:
# Exercise -- Do the array, column-wise and row-wise mean of A

A = np.array([[1,0,2,0],[0,3,0,4],[0,0,5,0],[6,0,0,7]])

print(A)

print(A.mean())
print(A.mean(0))
print(A.mean(1))

[[1 0 2 0]
 [0 3 0 4]
 [0 0 5 0]
 [6 0 0 7]]
1.75
[1.75 0.75 1.75 2.75]
[0.75 1.75 1.25 3.25]


In [122]:
# Exercise -- Do the array, column-wise and row-wise median of A 

A = np.array([[1,0,2,0],[0,3,0,4],[0,0,5,0],[6,0,0,7]])

print(A)

print(np.median(A))
print(np.median(A,axis=0))
print(np.median(A,axis=1))


[[1 0 2 0]
 [0 3 0 4]
 [0 0 5 0]
 [6 0 0 7]]
0.0
[0.5 0.  1.  2. ]
[0.5 1.5 0.  3. ]


[[1 0 2 0]
 [0 3 0 4]
 [0 0 5 0]
 [6 0 0 7]]
[[ 1.         -0.88662069  0.87038828 -0.34585723]
 [-0.88662069  1.         -0.56591646  0.2248724 ]
 [ 0.87038828 -0.56591646  1.         -0.57396402]
 [-0.34585723  0.2248724  -0.57396402  1.        ]]


In [135]:
# Exercise: Write a program that calculates the outputs of the first
# layer in the neural network in the slides. 
# with no activation function
# Assume random weights for the first layer

weight1 = np.random.random((2,4))
print(weight1)

input = np.array([[2,3]])
print(input)

out1 = np.dot(input,weight1)

print(out1)

# print shapes
print(input.shape)
print(weight1.shape)
print(out1.shape)


[[0.77060761 0.08273752 0.42057445 0.66329555]
 [0.77310994 0.26497958 0.87831131 0.66039794]]
[[2 3]]
[[3.86054503 0.96041379 3.47608282 3.3077849 ]]
(1, 2)
(2, 4)
(1, 4)


In [145]:
# Exercise: Write a program that calculates the final output of NN
# with ReLU activation function on all nodes
# Assume random weights for the both layers

def relu(X):
   return np.maximum(0,X)

weight1 = np.random.random((2,4))
print(weight1)
weight2 = np.random.random((4,1))
print(weight2)

input = np.array([[2,3]])
print(input)

out1 = relu(np.dot(input,weight1))
print(out1)
# note we need to transform out1
out2 = relu(np.dot(out1, weight2))
print(out2)
print(out2[0][0])


[[0.67141739 0.34266043 0.97820841 0.59641311]
 [0.47891273 0.31593436 0.44046009 0.46055303]]
[[0.24210622]
 [0.63023305]
 [0.20012261]
 [0.55389906]]
[[2 3]]
[[2.77957295 1.63312395 3.27779709 2.57448529]]
[[3.78416687]]
3.7841668677967917


In [153]:
# Exercise:  Write a forward function that returns the error between actual
# and predicted value calculated 

# x is a numpy array
# y is a number
# weights are numpy arrays
# initial weights 

# using arbirary weights
w1 = np.array([[0, -0.2, 0.5, -0.01],[0.3, -0.2, -0.1,0.9]])
w2 = np.array([[0.1, -0.1, 0.0001, 0.99]])
w2 = w2.T  #to get the right shape for multiply

def forward(x,y, weight1, weight2):
    out1 = relu(np.dot(input,weight1))
    out2 = relu(np.dot(out1, weight2))
    return abs(out2[0][0]-y)

x = np.array([[2,3]])
y = 5

print(forward(x,y,w1, w2))

2.25673
